/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package database.validation;


/**
 *
 * @author AdministratorJa
 */
public class EditCellNumbersFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditCellNumbersFrame
     */
    private final ConfigFile config = ConfigFile.GetInstance();
    
    public EditCellNumbersFrame() {
        initComponents();
        InitFields();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dailyWOClientNumberTextField = new javax.swing.JTextField();
        dailyWOClientNumberLabel = new javax.swing.JLabel();
        dailyWOMinTimeLabel = new javax.swing.JLabel();
        dailyWOMaxTimeLabel = new javax.swing.JLabel();
        dailyWOAddressLabel = new javax.swing.JLabel();
        dailyWOMinTimeTextField = new javax.swing.JTextField();
        dailyWOMaxTimeTextField = new javax.swing.JTextField();
        dailyWOAddressTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reportAddressTextField = new javax.swing.JTextField();
        reportMaxTimeTextField = new javax.swing.JTextField();
        reportClientNumberLabel = new javax.swing.JLabel();
        reportMinTimeLabel = new javax.swing.JLabel();
        reportClientNumberTextField = new javax.swing.JTextField();
        reportMinTimeTextField = new javax.swing.JTextField();
        reportMaxTimeLabel = new javax.swing.JLabel();
        reportAddressLabel = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dailyWOClientNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dailyWOClientNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dailyWOClientNumberLabel.setText("Numer komórki z numerem klienta");

        dailyWOMinTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dailyWOMinTimeLabel.setText("Numer komórki z minimalną godziną");

        dailyWOMaxTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dailyWOMaxTimeLabel.setText("Numer komórki z maksymalną godziną");

        dailyWOAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dailyWOAddressLabel.setText("Numer komórki z adresem");

        dailyWOMinTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dailyWOMaxTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dailyWOAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("DailyWO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Raport");

        reportAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        reportMaxTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        reportClientNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reportClientNumberLabel.setText("Numer komórki z numerem klienta");

        reportMinTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reportMinTimeLabel.setText("Numer komórki z minimalną godziną");

        reportClientNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        reportMinTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        reportMaxTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reportMaxTimeLabel.setText("Numer komórki z maksymalną godziną");

        reportAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reportAddressLabel.setText("Numer komórki z adresem");

        OKButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyWOClientNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dailyWOClientNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyWOMinTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dailyWOMinTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyWOMaxTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dailyWOMaxTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyWOAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dailyWOAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportClientNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportClientNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportMinTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportMinTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportMaxTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportMaxTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dailyWOClientNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailyWOClientNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dailyWOMinTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailyWOMinTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dailyWOMaxTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailyWOMaxTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dailyWOAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailyWOAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportClientNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportClientNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportMinTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportMinTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportMaxTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportMaxTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        SetValues();
        config.SaveConfigFile();
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCellNumbersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCellNumbersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCellNumbersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCellNumbersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCellNumbersFrame().setVisible(true);
            }
        });
    }
    
    private void InitFields()
    {
        dailyWOClientNumberTextField.setText(String.valueOf(config.getDailyWOClientNumberCell()));
        dailyWOMinTimeTextField.setText(String.valueOf(config.getDailyWOMinTimeCell()));
        dailyWOMaxTimeTextField.setText(String.valueOf(config.getDailyWOMaxTimeCell()));
        dailyWOAddressTextField.setText(String.valueOf(config.getDailyWOAddressCell()));
        reportClientNumberTextField.setText(String.valueOf(config.getReportClientNumberCell()));
        reportMinTimeTextField.setText(String.valueOf(config.getReportMinTimeCell()));
        reportMaxTimeTextField.setText(String.valueOf(config.getReportMaxTimeCell()));
        reportAddressTextField.setText(String.valueOf(config.getReportAddressCell()));
    }
    
    private void SetValues()
    {
        config.setDailyWOClientNumberCell(Integer.valueOf(dailyWOClientNumberTextField.getText()));
        config.setDailyWOMinTimeCell(Integer.valueOf(dailyWOMinTimeTextField.getText()));
        config.setDailyWOMaxTimeCell(Integer.valueOf(dailyWOMaxTimeTextField.getText()));
        config.setDailyWOAddressCell(Integer.valueOf(dailyWOAddressTextField.getText()));
        config.setReportClientNumberCell(Integer.valueOf(reportClientNumberTextField.getText()));
        config.setReportMinTimeCell(Integer.valueOf(reportMinTimeTextField.getText()));
        config.setReportMaxTimeCell(Integer.valueOf(reportMaxTimeTextField.getText()));
        config.setReportAddressCell(Integer.valueOf(reportAddressTextField.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel dailyWOAddressLabel;
    private javax.swing.JTextField dailyWOAddressTextField;
    private javax.swing.JLabel dailyWOClientNumberLabel;
    private javax.swing.JTextField dailyWOClientNumberTextField;
    private javax.swing.JLabel dailyWOMaxTimeLabel;
    private javax.swing.JTextField dailyWOMaxTimeTextField;
    private javax.swing.JLabel dailyWOMinTimeLabel;
    private javax.swing.JTextField dailyWOMinTimeTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel reportAddressLabel;
    private javax.swing.JTextField reportAddressTextField;
    private javax.swing.JLabel reportClientNumberLabel;
    private javax.swing.JTextField reportClientNumberTextField;
    private javax.swing.JLabel reportMaxTimeLabel;
    private javax.swing.JTextField reportMaxTimeTextField;
    private javax.swing.JLabel reportMinTimeLabel;
    private javax.swing.JTextField reportMinTimeTextField;
    // End of variables declaration//GEN-END:variables
}
